### ISSUE TITLE
Current with Darktable 4.0 release?

### ISSUE THREAD

**Issue by podiki** [aurelienpierreeng/ansel#10]
I appreciate all the work you've done on the technical side of Darktable and taking the time to clean up the UI for this fork. Can you clarify if the current commit is current with the upstream 4.0 release? I'm a little confused as GitHub hows this as forked from another fork of Darktable.

I guess this is somewhat specified in the wiki, but for more concreteness, will you make a release (or a tag) for a version that is a modified Darktable 4.0? Will you continue updating such a version or do you plan to always be based on the current git version of Darktable (or maybe maintain 2 branches, one for current Darktable release and one for git version)?

Thanks!

PS: For anyone using GNU Guix as a distro or package manager, I was able to build this fork with `guix build darktable --with-git-url=darktable=https://github.com/aurelienpierre/R-Darktable` or even better, run it directly with `guix shell darktable --with-git-url=darktable=https://github.com/aurelienpierre/R-Darktable -- darktable`. It just works.

**Comment by aurelienpierre** [comment]
The master branch of this fork is 100% compatible with darktable 4.0 and current darktable master regarding pixel processing code.

As of now, the current darktable master branch is used (mostly) for bugfixes over 4.0 in order to prepare the 4.1. Today, I resynced this fork's master on upstream darktable's master. So all these (R&Dt's master and upstream dt's master) are 4.0-compatible regarding edits.

I have published issues here today to announce the changes I want to do in the very immediate future to the ergonomics of dt. These changes are mostly cosmetic and harmless for actual pixel processing, and I want to get them done ASAP as a proof-of-concept to demonstrate what R&Dt is about and what my vision of design is. 

Once these are done and tested, I will release an "official" version of R&Dt 4.0 compatible with upstream dt 4.0, which will be essentially upstream dt's pipeline with different UI.

From there, what I wish to do is rolling releases on top of 4.0 as GUI changes go, for faster bug fixes and incremental design.

Regarding packaging, I have a working Win 10 box with everything set up to build dt, so I will provide Windows packages. I have got offers of help from various current dt's packagers for Linux distros, so it should be possible to roll Linux versions too. I need to investigate Flatpak and Appimages too, but with no guaranty on these fronts.

**Comment by payano** [comment]
Just a note regarding doing releases, it would be nice to generate installer packages for multiple platforms if the tests is passing so its easy to do just push out a new release when the code is stable enough. 

I can check if it's possible to do if you want.

Br,
Johan

**Comment by payano** [comment]
By the way, it would be nice to ship R&T with the latest lensfun version, we could always link it statically.

**Comment by aurelienpierre** [comment]
> Just a note regarding doing releases, it would be nice to generate installer packages for multiple platforms if the tests is passing so its easy to do just push out a new release when the code is stable enough.

Yes, we had @Johnybit try something like that with a nightly build workflow for Win on upstream darktable, it's still here, but it never worked. I agreee that, since CI is already building and starting the soft, it would be logical to finish the job and output a binary.

> I can check if it's possible to do if you want.

Gladly ! I guess your starter is in `.github/workflows` at the root of the project.

**Comment by payano** [comment]
Thanks, I'll give it a try when I'm back from vacation. 

By the way, if we don't have that much legacy, is it possible to maybe bump the lensfun version to the latest?

We could link the library statically if necessary. 😀

**Comment by podiki** [comment]
@aurelienpierre sounds good! I'm happy to submit a package for the Guix distro/package manager once you have a release. For Guix users they do have binary substitutes so it doesn't have to be built locally.

@payano not to get off topic here, but isn't lensfun supplied by the OS/distro? At least that's the case for the Linux distros I've been on, so that is a separate matter. (And as one that does some packaging now, much prefer software not bundling external dependencies if there isn't a strong reason, like specific changes or upstream issues.)
