### ISSUE TITLE
Intel Arc A750 not rendering NEF

### ISSUE THREAD

**Issue by dnlyko** [aurelienpierreeng/ansel#157]
Just installed new video card.

Seems to import the NEF but just displays solid black. 

 Renders fine in DT.

## System

* darktable version : 0.0.0+285~g0c37799cc
* OS                : Windows 11
* Linux - Distro    :
* Memory            :64
* Graphics card     :Intel Arc A750
* Graphics driver   :31.0.101.4369
* OpenCL installed  :
* OpenCL activated  :
* Xorg              :
* Desktop           :
* GTK+              :
* gcc               :
* cflags            :
* CMAKE_BUILD_TYPE  :

**Comment by dnlyko** [comment]
As it turns out, the DT version ( 4.3.0+2427~g8c49e89404) I tried it out on had turned off OpenGL.
It looks as though there is no Windows Ansel/DT support for Intel ARC GPUs

**Comment by olliwa-git** [comment]
have a look : 
https://discuss.pixls.us/t/solved-can-i-properly-enable-opencl-on-windows-11-and-intel-iris-xe-graphics-in-darktable-4-0/31600/23
https://github.com/darktable-org/darktable/pull/12155

**Comment by olliwa-git** [comment]
potentially the Intel drivers can cause problems, which is why they are blacklisted by default on the Microsoft OS, however it is possible to force its use by activating or deactivating the Intel driver by modifying the 8th parameter of the opencl device in the darktablerc file; for example for IRIS XE cards: cldevice_v4_intelririsrxegraphics=0 250 0 16 16 128 0 0 0.000000 0.000

**Comment by aurelienpierre** [comment]
Either update your OpenCL driver, entirely remove it or disable the GPU in Ansel from the `anselrc` file.
