### ISSUE TITLE
Exporting from darkroom should be possible

### ISSUE THREAD

**Issue by hatsunearu** [aurelienpierreeng/ansel#224]
There seems to be no way to export photos while in the darkroom view.

**Comment by aurelienpierre** [comment]
Yes, and that is a safety measure because in darkroom, you already have 2 image processing pipelines grabbing memory (thumbnail and full preview), so exporting (possibly at full res) opens a 3rd pipeline, and since the memory handling code is broken, it will attempt to spawn a pipe even if there is not enough (v)RAM left, resulting in crashes and loss of your edit.

To export, go back in lighttable, have only one pipeline processing at a time, reduce the surface for crashes.
