### ISSUE TITLE
Bug: Imported state tied to in-library state

### ISSUE THREAD

**Issue by sergiusens** [aurelienpierreeng/ansel#385]
### Code of Conduct

- [X] I have read this document and I accept the conditions

### Search previous report

- [X] I have searched my issue

### Computer's operating system

Linux

### What GPU do you have ?

Intel

### Ansel version

7f23d9d38

### Type of binary

Self-compiled (GCC or Clang)

### What happened?

If I import from my sdcard and later remove from the library, the file will show up as not imported when I want to import from the same sdcard again.

This is a problem when culling on the go.

### Does your problem occur with OpenCL enabled ?

Yes

### Does your problem occur with OpenCL disabled ?

Yes

**Comment by aurelienpierre** [comment]
If the file is not in library (because it was never imported or because it has been deleted), then the file is not imported as far as the library is concerned, and will be seen as such in importer. I don't see a bug here. 

The purpose of the "imported" state is to keep track of links between filesystems and library (database), which are otherwise not linked. 

The library is designed to keep track of the history of your files, so just keep everything imported in there. Removing images from library removes every reference to the files. It's sane and logical. It would be insane, dangerous, ambiguous and error-prone to keep any kind of data about a removed file (not to mention: how do you do garbage collection, then ?).
