### ISSUE TITLE
Increasing brightness in color eq causes noise/artefacts

### ISSUE THREAD

**Issue by RawConvert** [aurelienpierreeng/ansel#6]
ubuntu 20.04 R&Dt 3.9.0+1647~gebb12ab06 color EQ branch
i7 NO GPU

To reproduce - increase e.g. blue brightness, see artefacts.
E.g. in image below, blue brightening has affected the clouds.

![Screenshot from 2022-06-23 17-24-12](https://user-images.githubusercontent.com/16868433/175356826-9ac7dd05-3d1d-4d91-baa4-7f41f19880d7.png)

**Comment by aurelienpierre** [comment]
A guided filter is being worked to avoid that but the first results are not encouraging. This is what you get for willing to mess up with color in non-linear ways (hue is an angle).

**Comment by RawConvert** [comment]
>This is what you get for willing to mess up with color in non-linear ways (hue is an angle).

It sounds like you're blaming someone! - is that so?

**Comment by aurelienpierre** [comment]
It's not about blaming, it's an inherent problem caused by manipulating colors by their angle on the chromaticity diagram.

Take 2 almost neutral colors (grey-ish), they will have a delta E (perceptual color difference) very small. But it's perfectly possible that their computed hues are 90° or 180° apart. Doesn't matter to the eye, since their chroma is so small, but then, the hue-wise color change will not be the same at all since they record at very different hues. Hence the noise.

This is why we work in RGB as much as we can. Hue-wise color manipulations are brittle, which is why it's actually harmful to give too much flexibility in this module.

**Comment by RawConvert** [comment]
I hope the guided filter works out well then.
Changing the subject slightly, it seems to me the major part of this work is the Selection, i.e. determining which pixels to alter.  Applying the subsequent change to hue, brightness or saturation is relatively easy perhaps.  Is there merit in somehow making the selection a mask which is available to other modules, rather like creating a mask as currently on an Exposure instance say.  Putting it another way, if you're building a smart new selection process, why not make it available to all (pipe-subsequent) modules, not just Color Eq?

Also, what about having a Brightness slider so that when you choose a colour, you can restrict this with a brightness band, e.g. to work on mid browns but not bright orange.

**Comment by aurelienpierre** [comment]
I just want to remind you that whatever is done in color EQ is already perfectly doable in color balance using parametric masks on hue, chroma and brightness, and using the guided filter to ensure smooth blending. This method is much more robust.

The purpose of the color EQ is to provide a workflow shortcut to speed up the case where you might stack several instances of color balance masked on varying hues.

So, in the spirit of speeding up the basic, nice, use cases, I don't want to turn the UI into a turducken of features that are, anyway, duplicated.
