### ISSUE TITLE
Load lensfun from the project

### ISSUE THREAD

**Issue by aurelienpierre** [aurelienpierreeng/ansel#65]
Too many Linux distros ship outdated Lensfun libs. Users will need to run `lensfun-data-update` but most of them are not aware of that.

https://lensfun.github.io/manual/latest/dbsearch.html shows how to use a custom directory to load the data. The database should be loaded at building time, then CMake should be configured to install it somewhere like `/opt/ansel/share/lensfun` so the nightly packages are always up-to-date.

**Comment by aurelienpierre** [comment]
Actually, I'm verging on making it a submodule.

**Comment by AlynxZhou** [comment]
> Actually, I'm verging on making it a submodule.

I suggest to add it as a submodule, but don't static link and bundle the library, because what we need is only the database. Maybe we could copy to install the database, and load our install path with `lfDatabase::Load()`.

However I have another idea after <https://github.com/aurelienpierreeng/ansel/pull/85>, if the database `lensfun-data-update` downloaded is just `https://github.com/lensfun/lensfun/tree/master/data/db` dir, we could modify the CI script to checkout it, and replace the file that Ubuntu provides, so AppImages users always get latest database, and won't bother distros that dislike bundled libraries.

**Comment by aurelienpierre** [comment]
> Maybe another hack is to manually build the lensfun source in CI scripts, then install it both to Ubuntu root and AppDir, so we will both link and pack it into AppImage (Why we need to install it twice is because https://github.com/aurelienpierreeng/ansel/issues/54#issuecomment-1411709487, linuxdeploy cannot see liblensfun.so via libansel.so).

Given the issue #54 I think this is the sanest path indeed. If you can do it, that's even better !

**Comment by AlynxZhou** [comment]
> > Maybe another hack is to manually build the lensfun source in CI scripts, then install it both to Ubuntu root and AppDir, so we will both link and pack it into AppImage (Why we need to install it twice is because [#54 (comment)](https://github.com/aurelienpierreeng/ansel/issues/54#issuecomment-1411709487), linuxdeploy cannot see liblensfun.so via libansel.so).
> 
> Given the issue #54 I think this is the sanest path indeed. If you can do it, that's even better !

I'd like to try it today, but maybe check whether lensfun-update-data works fine first.

**Comment by AlynxZhou** [comment]
I just tested that `lensfun-update-data` works (see <https://github.com/AlynxZhou/ansel/actions/runs/4070532384/jobs/7011474895>), so we may not need to manually build it, just solve <https://github.com/aurelienpierreeng/ansel/issues/54> first then.

**Comment by aurelienpierre** [comment]
The DB update works but it's not boundled in the AppImage.

**Comment by AlynxZhou** [comment]
> The DB update works but it's not boundled in the AppImage.

Let me check this, I think we could add it (at least just manually copy `/var/lib/lensfun` to /usr/share/lensfun` should work).

**Comment by AlynxZhou** [comment]
> The DB update works but it's not boundled in the AppImage.

This should work, I tested on my system: <https://github.com/AlynxZhou/ansel/commit/a9a31727d4d4927b2754b69d93ebd3d3e0e05e59>.

I put this into building AppImage script instead of Workflow, so if someone wants to pack AppImage on their own system, they just run the script and will also pack lensfun database.

**Comment by AlynxZhou** [comment]
I guess this should be closed after <https://github.com/aurelienpierreeng/ansel/pull/86>.
