### ISSUE TITLE
RGB linear calculation of color-picker, preview, display and export

### ISSUE THREAD

**Issue by mediatechnologic** [aurelienpierreeng/ansel#68]
To my humble opinion the color picker and the previews and the image display 
in scaled (non-100%) darkroom edit mode do the wrong RGB calculations 
(non-linear RGB instead of linear RGB).

I do not want to copy all details from pixls and github again here.
May be Aurelien can have a view on this:
[https://discuss.pixls.us/t/rgb-calculation-color-picker-and-display-wrong-exposure-module-solved/34204](https://discuss.pixls.us/t/rgb-calculation-color-picker-and-display-wrong-exposure-module-solved/34204/27)

Here is also my simple checkerboard test file, which should stay for all zoom ratios with perceived 
and color picker light yellow (188,188,128) and NOT with light red(188,128,128): 
https://github.com/darktable-org/darktable/issues/12310#issuecomment-1374626148
![ey-checker_area_v20230106_green+magenta](https://user-images.githubusercontent.com/20679721/211174373-783746f8-2810-4587-9b30-eba916e69d81.png)

In addition I found, that also the JPG export of scaled down images is wrong in DT.
May be Ansel is more sensitive to correct such annoying limitations of RGB processing.

Thank you very much
Rudy

**Comment by aurelienpierre** [comment]
You are mixing unrelated stuff here.

The color picker gets the image buffer at the last stage of the pipeline, that is gamma-encoded and in display RGB space (so, possible gamut-clipped). To unfuck this mess, the whole thing needs to be rewritten to sample data earlier in the pipeline, before output color profile. I know that, and it's on my to-do list. 

But I don't see how this applies to preview and export, since interpolations are done before gamma (actually, you should call it OETF) encoding, in linear RGB.

**Comment by aurelienpierre** [comment]
Fixed. See https://ansel.photos/en/doc/modules/processing-modules/finalscale/
