### ISSUE TITLE
AppImage not build with CR3 support / old Exiv2 on Ubuntu 20.04

### ISSUE THREAD

**Issue by lartaud** [aurelienpierreeng/ansel#72]
**Describe the bug/issue**
I can’t import '.CR3' in Ansel because they do not show in the import dialog.

**To Reproduce**
1. Click on 'Open from disk...'
2. Select a folder containing '.CR3' files
3. '.CR3' files are not displayed

**Platform**
* Ansel version : Ansel-0.0.0+27~gd09679b3f-x86_64.AppImage
* OS                : 6.1.3-arch1-1
* Linux - Distro    : Arch Linux
* Memory            : 32GB
* Graphics card     : NVIDIA GeForce GTX 1060 6GB
* Graphics driver   : official nvidia drivers 525.78.01
* OpenCL installed  : opencl-nvidia 525.78.01
* OpenCL activated  : yes
* Xorg              : 21.1.6
* Desktop           : AwesomeWM
* GTK+              : 3.24.36

**Additional context**
 - If I copy a '.CR2' file in the folder, only it is shown as present.

**Comment by lartaud** [comment]
Oops…
copy pasted the wrong line: the Ansel version I used is:
Ansel-0.0.0+53~g664c527d3-x86_64.AppImage

**Comment by aurelienpierre** [comment]
Reproduced with the AppImage but not on a local build, so that should have something with either Libraw or Exiv2 versions on the Ubuntu 20.04 used to build the package.

**Comment by aurelienpierre** [comment]
Ok, mystery solved… Ubuntu 20.04 ships Exiv2 version 0.27.2 and CR3 support needs at least version 0.27.4. The problem I have is I don't see any repository providing 0.27.4 to Ubuntu 20.04.

**Comment by aurelienpierre** [comment]
I guess the least bad option is to add Exiv2 as a submodule, much like we do for Rawspeed and Libraw, to be able to control what version is used and with which flags it is built (for example, Fedora builds it without ISOBMFF/CR3 support even for recent versions, for fear of copyright issues). 

Seems that @AlynxZhou is better than me with CMake stuff, would that interest you ?

**Comment by AlynxZhou** [comment]
> Seems that @AlynxZhou is better than me with CMake stuff, would that interest you ?

Really? I first learnt CMake and find it's hard to understand for me then transfer all my projects into Meson. 😸

Nevermind, I'll try to help on it.

**Comment by aurelienpierre** [comment]
> Nevermind, I'll try to help on it.

Great, thanks !

**Comment by AlynxZhou** [comment]
So at least I have a may or may not work commit for this: <https://github.com/AlynxZhou/ansel/commit/c894791c41ac1a2acbdcc408b4a0c142cce848f9>.

But don't be happy, I (personally) think it's a dirty hack for some reasons after I really look into it:

1. Exiv2 itself is not designed as a bundled dep (unlike libraw or rawspeed), it has a command tool, and by default installs its libraries into system dir, so if you don't hack it, it will conflict with your system exiv2.
2. It's natural to try to static link it, but unfortunately I found both `libansel` and `ansel-curve-tool` depends on it, so I didn't do this. And it seems exiv2 still tries to install static libraries into system.
3. I've altered many variables to install exiv2 into `/usr/lib/ansel` instead of `/usr/lib` so it won't break system exiv2, and then `libansel` should load the bundled library via rpath, but I don't know how to let `ansel-curve-tool` to load it, it needs extra work.
4. Many linux distros dislike bundled libraries (for example Fedora), as a Linux distro engineer, I also suggest not enable this internal copy while packaging for them, and I really really don't want it to be only able to installed into `/opt`, that's why I need those hack.
5. I am not sure will this work on Windows, I hardly do development on Windows.

So even I have a commit for this, I don't like it, a typical distro way is to let user who don't have a exiv2 with features we need use some third party repos to install a newer exiv2 package, or just change their OS. Handling this in app is really not easy.

And I am not familiar with AppImage, so maybe you have different opinions, please tell me, thanks! It's too late here and I'll reply tomorrow.

**Comment by AlynxZhou** [comment]
Maybe it's better to handle it in the AppImage level instead of building level, I mean build and install a exiv2 normally and add it into AppImage, instead of as a submodule. And if user's distro has a lower version of exiv2, and they want cr3 support, they should use AppImage.

I am not sure how we package it for windows, but I think not all dependencies are submodules so exiv2 can also be handled in that way.

Just some thoughts and I'll try them tomorrow or later.

**Comment by AlynxZhou** [comment]
I see @lartaud is using Arch Linux, and I suggest you build this AUR package created by me: <https://aur.archlinux.org/packages/ansel-git>. Arch already has newer dependencies.

**Comment by AlynxZhou** [comment]
A question, does `linuxdeploy` read `AppimageBuilder.yml`? I don't see where it collect dependencies.

**Comment by AlynxZhou** [comment]
> A question, does `linuxdeploy` read `AppimageBuilder.yml`? I don't see where it collect dependencies.

I think I go to a wrong way, I find that I must let it link to our build of exiv2 when building appimage, just replace libraries are not enough.

I'd like to try to manually install exiv2 while setting up ci environment.

**Comment by AlynxZhou** [comment]
Now I have a better result, I modified the `lin-nightly` workflow that used to build AppImage, to let it fetch and build exiv2 0.27 from source, instead of install it from Ubuntu repo, and the final AppImage will link against and bundle the new one.

The commit is here: <https://github.com/AlynxZhou/ansel/commit/dc29536d7245d348f974675c56800eaea7fd7a3b>, I am not a CI/container guy so please help review it (Actually that's the first time I run GitHub Actions).

I triggered it manually and it builds: <https://github.com/AlynxZhou/ansel/actions/runs/4061513076/jobs/6991605343>, then I try to remove my system exiv2, download and run the AppImage, it works.

**Comment by AlynxZhou** [comment]
> I see @lartaud is using Arch Linux, and I suggest you build this AUR package created by me: https://aur.archlinux.org/packages/ansel-git. Arch already has newer dependencies.

And maybe I should update packaging dir later to tell Arch users use this PKGBUILD.

**Comment by AlynxZhou** [comment]
Also, if this solution is acceptable, maybe I could also use it for libraw, I guess many distros already packaged it, at least on my system, so I don't want to have a static linked copy...

**Comment by lartaud** [comment]
> I see @lartaud is using Arch Linux, and I suggest you build this AUR package created by me: https://aur.archlinux.org/packages/ansel-git. Arch already has newer dependencies.

I just tested it and it seems to work correctly.
Thanks!
