### ISSUE TITLE
Multiple selection in Filmstrip does not do anything ( + feature request?)

### ISSUE THREAD

**Issue by fedegst** [aurelienpierreeng/ansel#75]
**Describe the bug/issue**
In Darkroom, if I select multiple pictures from the filmstrip and then use keyboard shortcuts to perform operations only the opened picture is affected.

**To Reproduce**
1. Open  Picture A with darktable
2. Select other pictures in the filmstrip (Alt+click or Shift+click)
3. Use shortcuts to do something (Ctrl+V, 0 - 5, F1 - F4)
4. Only picture A is affected

**Expected behavior**
All the pictures in the selection are affected.

**Platform**
running appimage0.0.0+53~g664c527d3 on Ubuntu 22.04

---

**Additional comments**
I believe at some point darktable had a 'select on hoover' behavior that could also be used to affect pictures other than Picture A (not a huge fan, but better than nothing).

Since we are at it, I would like to point out that I find the Filmstrip kind of awkward to use (I must say I used to like it before the 'one click selects the image' behavior was introduced, sometime in 2020).

*My wish:* I am using darktable on a Desktop with mouse and keyboard, I mostly do light edits to batches of pictures to be shared with friends (no fine-art). My ideal workflow is:
1- edit one picture,
2- copy-paste the edits to the nearby pictures that look somewhat similar to have a starting point,
3- do finer tuning and decide which pictures look best,
4- make the pictures I am not satisfied with disappear by degrading/rejecting them.

I used to be able to do all of this without leaving the Darkroom, which was nice. For steps 2 and 4 I find it very convenient to use the Filmstrip, rather than jumping back and forth between Darkroom and Lighttable.

*My problems:* 
- with the current behavior I have to open the images one by one to make the modifications, which is way more inconvenient.
- I find it confusing that the open picture always counts as selected. More in general, when multiple pictures are selected I never quite know what will happen if I copy or paste the history stack (copy from where? Paste on which pictures?). I think that old darktable (pre 2020) was more transparent in these aspects.
- I am not sure I see the logic in making  the selected pictures of the filmstrip agree with the selected pictures of Lighttable. In my mind the former should just be a quick selection tool to do very basic operations, the latter selects which pictures to export, tag etc...

*One comment*: it seems a waste that the right click on Filmstrip does not do anything. Intuitively, I would expect it to raise a menu from which I can select copy/paste and be 100% sure that I am copy/pasting from/to the right picture.

If the answer is that I am using Ansel wrong and there is a better way, I am willing to accept it (but I do not think styles are the answer: these are usually travel pictures that require always different edits).

**Comment by ptilopteri** [comment]
unless you use the command-line version, it only works on one
image at a time.

ie:  ansel-cli <images>

**Comment by fedegst** [comment]
Is it the intended behavior? If so, the manual should be updated (https://ansel.photos/en/doc/modules/utility-modules/shared/filmstrip/). In that case I would also not see the point of allowing (multiple) selection at all in GUI, which is kind of buggy anyway.

One interesting undefined behavior is what happens if you press Ctrl+Shift+A to deselect all: the open picture will still show to be selected (as always) but it is actually not, as the keyboard shortcuts don't do anything on it.

**Comment by aurelienpierre** [comment]
The film strip only allows to open pictures from the current film roll (aka collection in darktable slang) from within the darkroom. Any digital asset management is to be done in the lighttable. Mixing file management with darkroom view is a can of worms and captures a lot of keyboard shortcuts that should be made available for image operations. 

Select on hover was removed because it's dangerous and brittle. See https://github.com/aurelienpierreeng/ansel/wiki#what-was-removed-from-mainstream-darktable for the full list.

Please open issues about only one topic at a time, so issues can be turned into task in the project management. For questions, use the discussion forum in the above tabs.

**Comment by fedegst** [comment]
Ok, understood. Then it may be wise to remove the (multiple) selection from darkroom altogether: at the moment is right-out confusing (and buggy).

_However,_ I would really like to re-implement the possibility of copying module settings from other pictures, at least via right-click menu. Two good reasons:
- many times while editing I realize that I need some module set up like in a previous picture (in the same film roll). Going through lightroom to fetch it is a disruption of the workflow.
- history does not behave well when pasting in lightroom (I can elaborate on this if you so wish).

Should I post this as a feature request?

**Comment by fedegst** [comment]
>  What is buggy ? Do you mean it does nothing or it has side-effects ?

I have encountered some buggy behaviors, but at the moment I cannot reproduce them. One that I remember was that pressing Ctrl+Shift+A secretly deselected also the displayed picture, so that using other shortcuts (e.g. to change rating) did not have any effect. I will write again if they manifest again.

> History copy-pasting is known to be broken (as well as styles) if you don't use the default pipeline order. It has been for a long time and I don't see a way to fix it. Is that what you mean ? And how does it behave better in darkroom ?

The problem I have is another (it is not a bug, but an inconvenient behavior). One issue is that if I do operations in lightroom and then open the darkroom, the history of the lightroom gets wiped. Case scenario where this is annoying:
- I copy a long history stack to a bunch of pictures,
- the thumbnails look ok, so I do not immediately revert with Ctrl+Z,
- I open one of those pictures, and I realized this history stack actually screwed something up,
- the only way to revert the changes now is to open the pictures one-by-one and manually look for the place in the history where the bad modifications were attached (using Ctrl+Z in darkroom does not do anything, because the changes come from the lightroom).

Pasting in darkroom can mitigate the problem, because I immediately see if something is off. 

If I remember correctly, it used to be the case that when pasting a history stack onto multiple pictures, this change could still be reverted one picture at the time by opening it and using Ctrl+Z. This would already be an improvement on the current behavior.

**Comment by aurelienpierre** [comment]
> I have encountered some buggy behaviors, but at the moment I cannot reproduce them. One that I remember was that pressing Ctrl+Shift+A secretly deselected also the displayed picture, so that using other shortcuts (e.g. to change rating) did not have any effect. I will write again if they manifest again.

Cool. The filmstrip thing was rewritten to use the same code as the lighttable, it's great to see that it doesn't behave the same. More fun times ahead to fix other people's shit.

> One issue is that if I do operations in lightroom and then open the darkroom, the history of the lightroom gets wiped. Case scenario where this is annoying:

That sounds like your history module is set on "overwrite" and you want to set it to "append".

> Pasting in darkroom can mitigate the problem, because I immediately see if something is off.

In darkroom, copying histories is forced to "append" mode.

> I copy a long history stack to a bunch of pictures,
the thumbnails look ok, so I do not immediately revert with Ctrl+Z,
I open one of those pictures, and I realized this history stack actually screwed something up,
the only way to revert the changes now is to open the pictures one-by-one and manually look for t

So that means thumbnails are not properly refreshed when they should ? I have noticed such behaviour myself, but not all the time, so it's hard to spot what's wrong.

**Comment by aurelienpierre** [comment]
I have cleaned up the mess in the filmstrip to make it behave like the lighttable thumbnails. Copy-pasting is restored on arbitrary selections but rating/rejecting is prevented as a safety measure because the overlay controls are too small to prevent misclick accidents.  The change will be in tonight's build.

**Comment by fedegst** [comment]
Thank you, it seems reasonable to me :)

One issue:
- the shortcuts for selective copy and paste are broken, both in lighttable and darkroom

Curious behaviors:
- open picture A in darkroom, ctrl+click on picture A, shift-click on picture B  --> no new pictures are selected (expected behavior: all the pictures between A and B are selected). Curiously enough, ctrl-c and ctrl-v still work on Picture A, so it is still selected, somehow.
- if multiple pictures in the filmstrip are selected, ctrl+c copies the history from the last picture that had been clicked. This is intuitive, but not coherent with the behavior in lighttable, where the history of the picture that come latest in the selection is taken (regardless of the order of clicks that made the selection in the first place).

One sad fact of life:
- open Picture A, paste history stack to Picture B in the filmstrip, regret your decision, press ctrl+z --> the paste action is not reverted, because ctrl+z only reverts the modifications to Picture A.

---

> That sounds like your history module is set on "overwrite" and you want to set it to "append".

No, I did not explain myself well. It does wipe the history from the database, only the 'local history' that can be reverted with ctrl+z. This 'local history' is lost every time a new picture is opened in darkroom.

> So that means thumbnails are not properly refreshed when they should ? I have noticed such behaviour myself, but not all the time, so it's hard to spot what's wrong.

Also not what I meant, I banally wanted to say that if the thumbnails are small I ma not notice that I screwed up something until it's too late. Now that you mention it, I do suspect that sometimes the thumbnails are not refreshed: I will keep an eye out for it and see if I find any reproducible issue.

**Comment by aurelienpierre** [comment]
> the shortcuts for selective copy and paste are broken, both in lighttable and darkroom

Shortcuts are user-defined, and only fall-back to defaults if nothing is set. Are you sure they are correctly set ?

> open picture A in darkroom, ctrl+click on picture A, shift-click on picture B --> no new pictures are selected (expected behavior: all the pictures between A and B are selected). Curiously enough, ctrl-c and ctrl-v still work on Picture A, so it is still selected, somehow.

I don't understand what shift/ctrl + click are supposed to do in this context. Could talk in terms of effect instead of shortcut ?

> if multiple pictures in the filmstrip are selected, ctrl+c copies the history from the last picture that had been clicked. This is intuitive, but not coherent with the behavior in lighttable, where the history of the picture that come latest in the selection is taken (regardless of the order of clicks that made the selection in the first place).

It's not consistent with the lighttable but consistent with the fact that, in darkroom, the currently opened image is always selected.

**Comment by fedegst** [comment]
I never touched the shortcuts myself before, they used to work just fine. Now I've done some testing, and on my build they acted funny, maybe because some defaults are changed?

- In the preferences shift+ctrl+c/v were assigned to "active view/selective copy/paste" (this seems to be used in lighttable) in the `utility modules/apply development` tab, and also to the "copy/paste history parts" in `other views/views/thumbtable` (this seems to be used in the filmstrip). By the way, it is a bit weird that the two entries have different names.
- If I used shift+ctrl+c in lighttable or darktable I got a pop-up saying "shift+ctrl+c not assigned".
- I manually added the same shortcuts again (so that they appeared twice under the same voice), then they started working fine. They kept working even after deleting this second entry.
- I then clicked on "restore" in the shortcuts menu, ticking the box "clear all newer shortcuts" and then restore to edits and defaults (I don't actually know what these should do). This deleted the the shift+ctrl+c/v shortcuts altogether.

Now I can still add them by hand and then they work is fine. Maybe the defaults had changed and Ansel didn't react to it as it should have? Small problem anyway.
 

>      I don't understand what shift/ctrl + click are supposed to do in this context. Could talk in terms of effect instead of shortcut ?

ctrl+click on a selected picture deselects it. If I do it on the open picture, it doesn't, because it is always selected. 
shift+click selects all the pictures from the one that was selected last to the one you just clicked.
If you did not select any picture and try to deselect the open picture with ctrl+click and then try to select other pictures with shift+click, then nothing happens. I'd say this means that ctrl+click to the open picture did have the effect that this no longer count as 'last selected picture' or something.... However, this is such a trivial problem that I wouldn't really waste time on it.

>      It's not consistent with the lighttable but consistent with the fact that, in darkroom, the currently opened image is always selected.

Speaking of, what is the advantage of having it always selected?

---

One little bug bonus:
If I do selective copy or paste and I do not select any module, then it pastes everything (instead of nothing).

**Comment by aurelienpierre** [comment]
> ctrl+click on a selected picture deselects it. If I do it on the open picture, it doesn't, because it is always selected.

That's normal in filmstrip from the darkroom view and is a limitation of trying to duplicate lighttable DAM features into the filmstrip. 

> Speaking of, what is the advantage of having it always selected?

None, it's a shitty design. "darktable selected" used to be an internal state of an image, independent from the "Gtk selected" (GUI) state. The picture being opened in darkroom was the "darktable selected" one. The pictures added to the GUI queue, for batch eding etc., were the "Gtk selected" pictures.

A moron thought it would be clever to re-use the "darktable selected" state for the culling view too, and re-did the whole thumbnail selection around the idea that "darktable selected" == "Gtk selected", and here we are. The "What You See Is What You Necessarily Want" idiots have consistently destroyed darktable usablity in the past 2 years because they don't get the difference between a view and a model. 

> Now I can still add them by hand and then they work is fine. Maybe the defaults had changed and Ansel didn't react to it as it should have? Small problem anyway.

Yes, I have removed the shortcuts for partial copy-pasting, provided that you need some sort of GUI to tell you what are the parts you copy and paste, and key shortcuts should be reserved for blind copy-pasting where you want the whole stack to be applied.

Also I have fixed a bug in the way key strokes are decoded with regard of key modifiers, so I guess everybody should refresh the shortcuts.

> If I do selective copy or paste and I do not select any module, then it pastes everything (instead of nothing).

Nice.

**Comment by aurelienpierre** [comment]
https://github.com/aurelienpierreeng/ansel/commit/8d9836e894ad95645c378c612b19403d1edd0838 fixes the issue : you can select any arbitrary set of pictures in filmstrip, without the selection having to include the one opened in darkroom. Only what you selected goes in the selection, making the filmstrip behaviour consistent with lighttable.

Feel free to reopen if I forgot something.
