### ISSUE TITLE
Lighttable UI should differentiate between 0 stars and 1 star

### ISSUE THREAD

**Issue by curiousercreative** [aurelienpierreeng/ansel#88]
**Did you buy darktable from an application store ?**
No

**Describe the bug/issue**
GUI defaults all imported images to 1 star it seems rather than 0 stars

**To Reproduce**
_Please provide detailed steps to reproduce the behaviour, for example:_
1. Import photos
2. In lighttable, enable overlays

**Expected behavior**
Images with no stars applied should be represented in UI as 0 stars

**Platform**
_Please fill as much information as possible in the list given below. Please state "unknown" where you do not know the answer and remove any sections that are not applicable _

* darktable version : Appimage downloaded today
* OS                : 6.0.12
* Linux - Distro    : Pop! 22.04
* Memory            : 128GB
* Graphics card     : 3080 Ti
* Graphics driver   : 525
* OpenCL installed  : y
* OpenCL activated  : y
* Xorg              :  1:7.7+23ubuntu2
* Desktop           : GNOME 42.5
* GTK+              : 
* gcc               : 
* cflags            : 
* CMAKE_BUILD_TYPE  :

**Comment by l-28** [comment]
Have you set the "initial rating" to 0 in the "Import Parameters"? The parameters expand under the “open from disk” and “import from camera” buttons. I ran into the same issue some time ago, because I forgot that there was the parameters thing. It's like a third place for import options apart from preferences and the import dialog.

https://ansel.photos/en/doc/modules/utility-modules/lighttable/import/#module-parameters

**Comment by curiousercreative** [comment]
Aha, I'll have a look! I'll close for now
