### ISSUE TITLE
the Ansel theme is very very bad in terms of visibility, readability, and accessibility

### ISSUE THREAD

**Issue by brigazvi** [aurelienpierreeng/ansel#91]
**What is the current problem you are facing ?**
the default (and only) color theme for Ansel have terrible contrast. it makes the text unreadable for people with color blindness and worsens the whole UX. I made some checks in Figma with a plugin called Contrast. but the internet is full of tools for such tests:
![dark backgroundtest](https://user-images.githubusercontent.com/37640970/217481495-d4be9ff7-150a-4552-a70b-7ef5a598a538.png)
![grey backgroundtest](https://user-images.githubusercontent.com/37640970/217481505-cb8f4bed-66c1-40e2-bfdb-c610b6b23b3e.png)
![light backgroundtest](https://user-images.githubusercontent.com/37640970/217481514-02a4e2dd-7593-4d4b-931f-0b19f22a316e.png)

as you clearly see, it fails a lot of the tests. especially when we talk about small text. the easy solution is to make the whole background much darker.

**Where in your workflow does your problem occur ?**
when I open the app.

**Additional context**
I would love to help with this, but I don't know how to build themes. I know CSS if it helps. I someone could point me in the right direction maybe I would find the time to work on something. or maybe we should just take the Darktable theme. if it ain't broke don't fix it.

**Comment by l-28** [comment]
Hey @brigazvi,

I have been following the Ansel development for some time as a user. The topic of the themes and GUI design pops up every now and then. There has also been a dedicated community call to discuss the matter (which I couldn't attend so I'm not sure of the outcomes). 

The tests you ran give a good insight in why as users the Ansel theme looks a bit off. On the other hand they sort of indicate, that one of the design goals of the theme have been achieved: to have an interface that influences the perception of an image as little as possible. To quote @aurelienpierre in one of the longer GUI design discussions "the design constraints here are pretty stiff, given that there is a lot to fit in the GUI while trying to stay low-contrast at the verge of unlegible" (taken from [Matrix Chat - Ansel English](https://matrix.to/#/#r&darktable-en:matrix.org))

Following this reasoning the darktable theme is considered broken:

 "dark themes trigger all sorts of unwanted visual illusions that make color assessment impossible. Their use is discouraged everywhere on darktable’s doc but they are still there." ([Ansel Doc](https://ansel.photos/en/doc/special-topics/from-darktable/#features)) 


I do understand your point very well, in fact when I first installed Ansel, the very first thing I did was changing the look of the theme. But after all those discussions I now use the default Ansel theme - not because I like the looks of it but because it seems better suited.

**Comment by brigazvi** [comment]
hi @l-28, thanks for the quick response.

> "dark themes trigger all sorts of unwanted visual illusions that make color assessment impossible. Their use is discouraged everywhere on darktable’s doc but they are still there." ([Ansel Doc](https://ansel.photos/en/doc/special-topics/from-darktable/#features))

if the problem is with the dark theme, we can make it light and still readable. like, we can make the buttons black.

if we must have a grey theme, then we have to use solutions like drop shadow for white text or something, to make it with more contrast.

if the problem is high contrast buttons, then we are in a big problem, and we need a very creative way to solve it. for example, every time you move a slider in a module, the image goes full screen so you can see the changes without visual illusions.

I think that unreadable buttons are not less of a problem than visual illusions.

**Comment by brigazvi** [comment]
from what I saw now in the Darktable docs, the main issue is with the main shade of grey of the surroundings of the image. we can do a lot to make icons and buttons more readable in those circumstances.
drop shadow for text and black container for icons or buttons are more than enough for this kind of thing.
if I'm repeating the same arguments and discussion that has been done already, and the developers don't want to hear about it, please point me to the discussion and we can close this issue.
but right now, it seems to me like we can do a lot about it.

**Comment by brigazvi** [comment]
just found out the theme development part of the documentation of Darktable. I will try to make something and post it here.

**Comment by l-28** [comment]
I don't know the theme development part of the darktable documentation, but you should keep in mind that part of the reasons for the Ansel fork were design related. So I'm not sure whether what you are referring to is applicable. 

Furthermore I would suggest that you try to get the information on what has already been discussed before doing any work to save yourself from some pitfalls. Unfortunately I'm not aware of any public notes on the GUI meeting.

**Comment by aurelienpierre** [comment]
This is not a text editor and I'm too lazy to explain once again why things are how they are, but there are good reasons.

**Comment by brigazvi** [comment]
>This is not a text editor and I'm too lazy to explain once again why things are how they are, but there are good reasons.

That's was fast. I'm a little bit shocked. But I respect your decision. I will find another projects to contribute to with my UI/UX skills. But if you want to make this a better software in terms of UX (which is the whole point of this fork) , you will need to find a better and more transparent way to discuss decisions, a way you can refer to later, point new contributors to, and can improve upon.

It's funny to me how in the video about the fork @aurelienpierre said that Darktable wasn't open to criticism about design decisions. If you want to do better you have to find better ways to manage the UX workflow.

Maybe later I will post here some of the work I did yesterday on a new grey theme. You can do with it whatever you want.

**Comment by brigazvi** [comment]
![תמונה](https://user-images.githubusercontent.com/37640970/217742281-7d3101e9-0faa-406f-bdda-1cdb5d9f5d84.png)

-Work In Progress (or not)

**Comment by pedrorrodriguez** [comment]
> we can do a lot to make icons and buttons more readable in those circumstances. drop shadow for text and black container for icons or buttons are more than enough for this kind of thing. if I'm repeating the same arguments and discussion that has been done already, and the developers don't want to hear about it, please point me to the discussion and we can close this issue. but right now, it seems to me like we can do a lot about it.

I thought the same, but apparently not. Everything needs to stay as close to middle grey as possible. Drop shadows, borders etc. will affect perception. It was discussed at length in the matrix chat, but I don't know if you can access the messages. The issue is known, and there might be improvements coming at some point.

**Comment by aurelienpierre** [comment]
> It's funny to me how in the video about the fork @aurelienpierre said that Darktable wasn't open to criticism about design decisions. If you want to do better you have to find better ways to manage the UX workflow.

First, try to understand the constraints and reasons for the current design. They are grounded in color science and in the shit load of visual illusions and perceptual problems that stem from having contrasty things around the image.

Once you get that, you will understand why improving legibility will be made at the expense of color assessment.
